#!/bin/bash
#Ask user for variables:

#echo Site:
#read site
echo Community String:
read community_string_v2

sed "s/<COMMUNITY_STRING>/$community_string_v2/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml

#sed "s/<SITE>/$site/g" /etc/datadog-agent/conf.d/ping.d/conf.yaml
#sed "s/<SITE>/$site/g" /etc/datadog-agent/conf.d/speedtest.d/conf.yaml
#sed "s/<SITE>/$site/g" /etc/datadog-agent/conf.d/tcp_check.d/conf.yaml
#sed "s/<SITE>/$site/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml

#sed "s/<FIREWALL_IP>/$firewall_ip/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml
#sed "s/<authKey>/$authkey_v3/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml
#sed "s/<privKey>/$privkey_v3/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml
#sed "s/<PRINTER_VLAN>/$printer_vlan/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml
#sed "s/<COMMUNITY_STRING>/$community_string_v2/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml
#sed "s/<NETWORK_MANAGEMENT_VLAN>/$network_management_vlan/g" /etc/datadog-agent/conf.d/snmp.d/conf.yaml
