source s_network_port {
        network(transport(udp) port(514));
};
#destination d_logs {
#    file(
#        "/var/log/sophos.log"
#        owner("root")
#        group("root")
#        perm(0777)
#        );
#    };


template DatadogFormat { template("DD_API_KEY <${PRI}>1 ${ISODATE} ${HOST:--} ${PROGRAM:--} ${PID:--} ${MSGID:--} [metas@0 ddsource=\"snmppoller-SITE\" ddtags=\"site:SITE,function:logcollector\"] $MSG\n"); };

destination d_datadog { tcp("intake.logs.datadoghq.com" port(10514) template(DatadogFormat)); };

#log { source(s_network_port); destination(d_logs); };
log { source(s_network_port); destination(d_datadog); };